/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import generator.CertificateGenerator;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jhone
 */
public class view extends javax.swing.JFrame {
    
    private CertificateGenerator controller;
    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        avisoLabel.setVisible(false);
        statusLabel.setVisible(false);
        controller = new CertificateGenerator();
        controller.carregar();
        ImageIcon cv = new ImageIcon(controller.getIMAGE());
        templateLabel.setIcon(new ImageIcon(cv.getImage().getScaledInstance(400, 282, Image.SCALE_DEFAULT)));
        
        DefaultListModel modelo = new DefaultListModel();
        ArrayList<ArrayList<String>> config = controller.getText2();
        for(int i=0;i<config.size();i++){
            if(!config.get(i).get(0).equals("imgPath"))
                modelo.addElement(config.get(i).get(0));
        }
        fullTextArea.setLineWrap(true);
        fullTextArea.setText(controller.getText1()+"João da Silva Exemplo participou do palestra: " +
                "Introdução ao Conhecimento Científico, com a carga horária de XX" +
                "horas, na "+controller.getFinal());
        jList1.setModel(modelo);
        
        editTextArea.setLineWrap(true);
        repaint();
    }
    
    @Override
    public void paint (Graphics g){
        super.paint(g);
        
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);    
        
        ImageIcon warning = new ImageIcon("src/view/warning.png");
        g2.drawImage(warning.getImage(), templateLabel.getX(), templateLabel.getY()+25, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        principal = new javax.swing.JPanel();
        templateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        addCategoriaButton = new javax.swing.JButton();
        addCategoriaTextField = new javax.swing.JTextField();
        delCategoriaButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        javax.swing.JLabel visualizacaoLabel = new javax.swing.JLabel();
        salvarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        editarRadioButton1 = new javax.swing.JRadioButton();
        editarRadioButton2 = new javax.swing.JRadioButton();
        mudarTemplateButton = new javax.swing.JButton();
        avisoLabel = new javax.swing.JLabel();
        gerarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        editTextArea = new javax.swing.JTextArea();
        participanteLabel = new javax.swing.JLabel();
        palestranteLabel = new javax.swing.JLabel();
        ordenarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fullTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        instrucoesLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        instrucoes = new javax.swing.JPanel();
        principalLabel1 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        insText1Label = new javax.swing.JLabel();
        insText2Label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ex2Label = new javax.swing.JLabel();
        ex1Label = new javax.swing.JLabel();
        ex3Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de certificados");
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/view/icon.png"));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        principal.setPreferredSize(new java.awt.Dimension(900, 600));

        templateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/template.jpg"))); // NOI18N
        templateLabel.setText("template");
        templateLabel.setToolTipText("");
        templateLabel.setPreferredSize(new java.awt.Dimension(200, 200));

        jList1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "palestra", "oficina", "palestra", "participacao", "monitor", "organizacao" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CATEGORIAS:");

        addCategoriaButton.setActionCommand("addCategoria");
        addCategoriaButton.setLabel("Adicionar");
        addCategoriaButton.setMaximumSize(new java.awt.Dimension(75, 23));
        addCategoriaButton.setMinimumSize(new java.awt.Dimension(75, 23));
        addCategoriaButton.setPreferredSize(new java.awt.Dimension(75, 23));
        addCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoriaButtonActionPerformed(evt);
            }
        });

        addCategoriaTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        delCategoriaButton.setLabel("Deletar");
        delCategoriaButton.setMaximumSize(new java.awt.Dimension(75, 23));
        delCategoriaButton.setMinimumSize(new java.awt.Dimension(75, 23));
        delCategoriaButton.setPreferredSize(new java.awt.Dimension(75, 23));
        delCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCategoriaButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLabel.setText("Gerador de Certificados");

        visualizacaoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visualizacaoLabel.setText("VISUALIZAÇÃO:");

        salvarButton.setText("Salvar");
        salvarButton.setEnabled(false);
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("SUB-CATEGORIAS:");

        buttonGroup1.add(editarRadioButton1);
        editarRadioButton1.setSelected(true);
        editarRadioButton1.setText("Editar");
        editarRadioButton1.setActionCommand("editar1");
        editarRadioButton1.setEnabled(false);
        editarRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(editarRadioButton2);
        editarRadioButton2.setText("Editar");
        editarRadioButton2.setActionCommand("editar1");
        editarRadioButton2.setEnabled(false);
        editarRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarRadioButton2ActionPerformed(evt);
            }
        });

        mudarTemplateButton.setText("Mudar Template");
        mudarTemplateButton.setToolTipText("");
        mudarTemplateButton.setActionCommand("mudarTemplate");
        mudarTemplateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarTemplateButtonActionPerformed(evt);
            }
        });

        avisoLabel.setForeground(new java.awt.Color(255, 0, 0));
        avisoLabel.setText("Não é permitido caracteres especiais");
        avisoLabel.setToolTipText("");

        gerarButton.setBackground(new java.awt.Color(100, 255, 150));
        gerarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gerarButton.setText("Gerar");
        gerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarButtonActionPerformed(evt);
            }
        });

        editTextArea.setColumns(20);
        editTextArea.setRows(5);
        jScrollPane2.setViewportView(editTextArea);

        participanteLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        participanteLabel.setText("Participante");

        palestranteLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        palestranteLabel.setText("Palestrante");

        ordenarButton.setText("Ordenar");
        ordenarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarButtonActionPerformed(evt);
            }
        });

        fullTextArea.setEditable(false);
        fullTextArea.setColumns(20);
        fullTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        fullTextArea.setRows(5);
        jScrollPane3.setViewportView(fullTextArea);

        jLabel3.setText("Visualizar texto");

        instrucoesLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instrucoesLabel.setText("Instruções");
        instrucoesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instrucoesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                instrucoesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                instrucoesLabelMouseExited(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(0, 0, 255));
        statusLabel.setText("Status");

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrucoesLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(principalLayout.createSequentialGroup()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(principalLayout.createSequentialGroup()
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addGap(0, 32, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel3)
                                        .addGap(225, 225, 225)
                                        .addComponent(mudarTemplateButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(principalLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(visualizacaoLabel)
                                    .addComponent(templateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(avisoLabel)
                                .addGroup(principalLayout.createSequentialGroup()
                                    .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(addCategoriaTextField)
                                        .addComponent(jScrollPane1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                                            .addComponent(delCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(addCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(principalLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalLayout.createSequentialGroup()
                                                        .addComponent(participanteLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                                        .addComponent(editarRadioButton1))
                                                    .addGroup(principalLayout.createSequentialGroup()
                                                        .addComponent(palestranteLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(editarRadioButton2)))))
                                        .addGroup(principalLayout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(salvarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(statusLabel)
                                .addGroup(principalLayout.createSequentialGroup()
                                    .addComponent(ordenarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(gerarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleLabel)
                        .addGap(211, 211, 211)))
                .addGap(30, 30, 30))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrucoesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualizacaoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addComponent(templateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(principalLayout.createSequentialGroup()
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(editarRadioButton1)
                                    .addComponent(participanteLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(editarRadioButton2)
                                    .addComponent(palestranteLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avisoLabel)
                        .addGap(7, 7, 7)
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salvarButton)
                            .addComponent(addCategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statusLabel)
                        .addGap(21, 21, 21)))
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ordenarButton)
                    .addComponent(gerarButton)
                    .addComponent(mudarTemplateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(principal, "card2");

        principalLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        principalLabel1.setText("Principal");
        principalLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                principalLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                principalLabel1MouseExited(evt);
            }
        });

        resetButton.setText("Redefinir Configurações");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        insText1Label.setText("Transcreva as listas para um ou mais arquivos txt. Coloque o(s) txt(s) em uma pasta com o nome \"in\" no mesmo diretório da aplicação (criar, caso não tenha).");
        insText1Label.setToolTipText("");

        insText2Label.setText("Abra a aplicação, edite as configurações que achar interessante e clique em gerar. Os certificados gerados estarão na pasta results no mesmo diretório da aplicação.");
        insText2Label.setToolTipText("");

        jLabel4.setText("É recomendável o uso da função \"Ordenar\", que replica os txts existentes na pasta \"in\" com seus conteúdos em ordem alfabética. Útil para ver casos de repetições");

        jLabel5.setText("Exemplo de txt:");

        jLabel6.setText("Dica: Participações em palestras geram certificado de participação do evento. Assim pode declarar todas as palestras, afim de gerar certificados dos palestrantes");

        jLabel7.setText("e por os nomes de todos os participantes abaixo, assim depois de usar a ferramenta de ordenação, evitará certificados duplicados.");

        ex2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ex2.png"))); // NOI18N

        ex1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ex1.png"))); // NOI18N

        ex3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ex3.png"))); // NOI18N
        ex3Label.setToolTipText("");

        javax.swing.GroupLayout instrucoesLayout = new javax.swing.GroupLayout(instrucoes);
        instrucoes.setLayout(instrucoesLayout);
        instrucoesLayout.setHorizontalGroup(
            instrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrucoesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(instrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(insText2Label)
                    .addComponent(insText1Label)
                    .addComponent(jLabel7)
                    .addGroup(instrucoesLayout.createSequentialGroup()
                        .addComponent(ex1Label)
                        .addGap(18, 18, 18)
                        .addComponent(ex2Label)
                        .addGap(18, 18, 18)
                        .addComponent(ex3Label)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(instrucoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principalLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addGap(85, 85, 85))
        );
        instrucoesLayout.setVerticalGroup(
            instrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrucoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(principalLabel1)
                    .addComponent(resetButton))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(insText1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insText2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(instrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ex2Label)
                    .addComponent(ex1Label)
                    .addComponent(ex3Label))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(instrucoes, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoriaButtonActionPerformed
        if (addCategoriaTextField.getText().isEmpty()||addCategoriaTextField.getText().equals(" ")){
            avisoLabel.setVisible(false);
            return;
        }
        
        if(addCategoriaTextField.getText().replaceAll("[^A-Za-z0-9 ]", "").trim().isEmpty()){
            avisoLabel.setText("Não é permitido caracteres especiais");
            avisoLabel.setVisible(true);
            return;
        }
        if(addCategoriaTextField.getText().replaceAll("[0-9]", "+").trim().charAt(0)=='+'){
            avisoLabel.setText("Não pode iniciar com números");
            avisoLabel.setVisible(true);
            return;
        }
        avisoLabel.setVisible(false);
        DefaultListModel modelo = new DefaultListModel();
        for(int i=0; i<jList1.getModel().getSize();i++)
            modelo.addElement(jList1.getModel().getElementAt(i));
        modelo.addElement(addCategoriaTextField.getText());
        ArrayList<String> listTemp = new ArrayList<>();
        ArrayList<String> listTemp2 = new ArrayList<>();
        listTemp.add(addCategoriaTextField.getText());
        listTemp.add("");
        listTemp.add("");
        listTemp2 = controller.getText2().get(controller.getText2().size()-1);
        controller.getText2().remove(controller.getText2().size()-1);
        controller.getText2().add(listTemp);
        controller.getText2().add(listTemp2);
        
        addCategoriaTextField.setText("");
        jList1.setModel(modelo);
    }//GEN-LAST:event_addCategoriaButtonActionPerformed

    private void delCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCategoriaButtonActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        for(int i=0; i<jList1.getModel().getSize();i++){
            if(jList1.getSelectedIndex()!=i)
                modelo.addElement(jList1.getModel().getElementAt(i));                
        }
        controller.getText2().remove(jList1.getSelectedIndex());
        jList1.setModel(modelo);
        
        editTextArea.setText("");
        editarRadioButton1.setEnabled(false);
        editarRadioButton2.setEnabled(false);
        editTextArea.setEnabled(false);
        salvarButton.setEnabled(false);
        salvar();
    }//GEN-LAST:event_delCategoriaButtonActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(jList1.getSelectedIndex()<0)
            return;
        editTextArea.setText(controller.getText2().get(jList1.getSelectedIndex()).get(1));
        String nomeCompare = controller.getText2().get(jList1.getSelectedIndex()).get(0);
        if (nomeCompare.equals("palestra")||nomeCompare.equals("organizacao")||nomeCompare.equals("monitor")||nomeCompare.equals("final"))
            delCategoriaButton.setEnabled(false);
        else
            delCategoriaButton.setEnabled(true);
        editarRadioButton2.setEnabled(false);
        if(controller.getText2().get(jList1.getSelectedIndex()).size()>2){
            editarRadioButton2.setEnabled(true);
        }
        if(jList1.getSelectedIndex()>0){
            if (jList1.getModel().getElementAt(jList1.getSelectedIndex()).equals("palestra"))
                fullTextArea.setText(controller.getText1()+"João da Silva Exemplo"+editTextArea.getText()+
                ", com a carga horária de XX" +
                " horas, na "+controller.getFinal());
            else
                fullTextArea.setText(controller.getText1()+"João da Silva Exemplo"+editTextArea.getText()+
                "Introdução ao Conhecimento Científico, com a carga horária de XX" +
                " horas, na "+controller.getFinal());
        }
        editarRadioButton1.setEnabled(true); 
        editarRadioButton1.setSelected(true);
        editTextArea.setEnabled(true);
        salvarButton.setEnabled(true);
    }//GEN-LAST:event_jList1ValueChanged

    private void mudarTemplateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarTemplateButtonActionPerformed
        JFileChooser abrir = new JFileChooser();  
        abrir.setAcceptAllFileFilterUsed(false);
        abrir.addChoosableFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "tif"));        
        int retorno = abrir.showOpenDialog(null);  
        String caminho ="";
        if (retorno==JFileChooser.APPROVE_OPTION)  
            caminho = abrir.getSelectedFile().getAbsolutePath();
        //System.out.println(caminho);
        if(!caminho.isEmpty())
            controller.setIMAGE(caminho);
        ImageIcon cv = new ImageIcon(controller.getIMAGE());
        templateLabel.setIcon(new ImageIcon(cv.getImage().getScaledInstance(400, 282, Image.SCALE_DEFAULT)));
        try {
            controller.salvar();
        } catch (IOException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
    }//GEN-LAST:event_mudarTemplateButtonActionPerformed

    private void gerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarButtonActionPerformed
        statusLabel.setVisible(true);
                
        try {
            statusLabel.setText("executando...");
            controller.run();
            statusLabel.setText("Gerado com sucesso!");
        } catch (IOException | DocumentException ex) {
            statusLabel.setText("Falha na geração, cheque o arquivo de entrada!");
            statusLabel.setVisible(true);
        }
        
    }//GEN-LAST:event_gerarButtonActionPerformed

    private void editarRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarRadioButton1ActionPerformed
        if(jList1.getSelectedIndex()<0)
            return;
        editTextArea.setText(controller.getText2().get(jList1.getSelectedIndex()).get(1));
        editarRadioButton1.setSelected(true);
        editarRadioButton2.setSelected(false);
        editarRadioButton2.setEnabled(false);
        if(controller.getText2().get(jList1.getSelectedIndex()).size()>2){
            editarRadioButton2.setEnabled(true);
        }
        if(jList1.getSelectedIndex()>0){
            if (jList1.getModel().getElementAt(jList1.getSelectedIndex()).equals("palestra"))
                fullTextArea.setText(controller.getText1()+"João da Silva Exemplo"+editTextArea.getText()+
                ", com a carga horária de XX" +
                " horas, na "+controller.getFinal());
            else
                fullTextArea.setText(controller.getText1()+"João da Silva Exemplo"+editTextArea.getText()+
                "Introdução ao Conhecimento Científico, com a carga horária de XX" +
                " horas, na "+controller.getFinal());
        }
    }//GEN-LAST:event_editarRadioButton1ActionPerformed

    private void editarRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarRadioButton2ActionPerformed
        if(jList1.getSelectedIndex()<0)
            return;
        
        editarRadioButton2.setSelected(true);
        editarRadioButton1.setSelected(false);
        editTextArea.setText("");
        if(controller.getText2().get(jList1.getSelectedIndex()).size()>2){
            editTextArea.setText(controller.getText2().get(jList1.getSelectedIndex()).get(2));
        }
        if(jList1.getSelectedIndex()>0)
            fullTextArea.setText(controller.getText1()+"João da Silva Exemplo"+editTextArea.getText()+
                "Introdução ao Conhecimento Científico, com a carga horária de XX" +
                " horas, na "+controller.getFinal());
    }//GEN-LAST:event_editarRadioButton2ActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        if(editarRadioButton1.isSelected()){
            controller.getText2().get(jList1.getSelectedIndex()).set(1, editTextArea.getText());
        }else
            controller.getText2().get(jList1.getSelectedIndex()).set(2, editTextArea.getText());
        try {
            controller.salvar();
        } catch (IOException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void ordenarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarButtonActionPerformed
        try {
            controller.ordenar();
        } catch (IOException ex) {
            statusLabel.setText("Falha na ordenação, cheque o arquivo de entrada!");
            statusLabel.setVisible(true);
        }
        statusLabel.setText("Ordenado com sucesso!");
        statusLabel.setVisible(true);
    }//GEN-LAST:event_ordenarButtonActionPerformed

    private void instrucoesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrucoesLabelMouseEntered
        instrucoesLabel.setFont(new Font("Tahoma", Font.BOLD, 13));
    }//GEN-LAST:event_instrucoesLabelMouseEntered

    private void instrucoesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrucoesLabelMouseExited
        instrucoesLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_instrucoesLabelMouseExited

    private void instrucoesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrucoesLabelMouseClicked
        principal.setVisible(false);
        instrucoes.setVisible(true);
    }//GEN-LAST:event_instrucoesLabelMouseClicked

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        controller.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void principalLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalLabel1MouseExited
        principalLabel1.setFont(new Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_principalLabel1MouseExited

    private void principalLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalLabel1MouseEntered
        principalLabel1.setFont(new Font("Tahoma", Font.BOLD, 13));
    }//GEN-LAST:event_principalLabel1MouseEntered

    private void principalLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalLabel1MouseClicked
        principal.setVisible(true);
        instrucoes.setVisible(false);
        repaint();
    }//GEN-LAST:event_principalLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoriaButton;
    private javax.swing.JTextField addCategoriaTextField;
    private javax.swing.JLabel avisoLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delCategoriaButton;
    private javax.swing.JTextArea editTextArea;
    private javax.swing.JRadioButton editarRadioButton1;
    private javax.swing.JRadioButton editarRadioButton2;
    private javax.swing.JLabel ex1Label;
    private javax.swing.JLabel ex2Label;
    private javax.swing.JLabel ex3Label;
    private javax.swing.JTextArea fullTextArea;
    private javax.swing.JButton gerarButton;
    private javax.swing.JLabel insText1Label;
    private javax.swing.JLabel insText2Label;
    private javax.swing.JPanel instrucoes;
    private javax.swing.JLabel instrucoesLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton mudarTemplateButton;
    private javax.swing.JButton ordenarButton;
    private javax.swing.JLabel palestranteLabel;
    private javax.swing.JLabel participanteLabel;
    private javax.swing.JPanel principal;
    private javax.swing.JLabel principalLabel1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton salvarButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel templateLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
